######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 4 15:48:25 2014
######################################################################

TEMPLATE = lib
CONFIG = staticlib
TARGET = picojpeg
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += picojpeg.h
SOURCES += picojpeg.c
